version: '3'

networks:
  dev-network:
    driver: bridge

services:
##### PHP - Apache #####
  php-apache:
    build:
      dockerfile: ./php-apache/Dockerfile
      context: .
      args:
        - PHP_VERSION=${ENV_PHP_VERSION}
    volumes:
      - ${ENV_PATH_PROJECT}:/var/www/html:cached
      - ${ENV_PATH_CUSTON_BASH}:/var/www/bash-env
      - ${ENV_PATH_LOGS}/apache:/var/log/apache2
      - ./php-apache/apache-config/sites:/etc/apache2/sites-available
    ports:
      - ${ENV_APACHE_PORT}:80
      - ${ENV_APACHE_SSL_PORT}:443
    networks:
      dev-network:
        aliases:
          - vendas.localhost.com

##### Mysql #####
  mysql:
    build:
      dockerfile: ./mysql/Dockerfile
      context: .
      args:
        - MYSQL_VERSION=${ENV_MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${ENV_MYSQL_DATABASE}
      - MYSQL_USER=${ENV_MYSQL_USER}
      - MYSQL_PASSWORD=${ENV_MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${ENV_MYSQL_ROOT_PASSWORD}
    volumes:
      - ${ENV_PATH_STORAGE}/mysql:/var/lib/mysql
      - ./mysql/scripts-sql:/docker-entrypoint-initdb.d
    ports:
      - ${ENV_MYSQL_PORT}:3306
    networks:
      - dev-network